### ISSUE TITLE
Sound | Card Played

### ISSUE THREAD

**Issue by emmettirl** [Teicsoft/GLADIATE#157]

**Comment by cruxlime** [comment]
Merge https://github.com/Teicsoft/GLADIATE/pull/169 contains a card draw sfx, need someone else to QC it at https://github.com/Teicsoft/GLADIATE/blob/main/assets/audio/sfx/drawn-card.ogg to see if it's appropriate.

**Comment by cruxlime** [comment]
General consensus is that this works for card played, closing.
