### ISSUE TITLE
Status Indicator

### ISSUE THREAD

**Issue by emmettirl** [Teicsoft/GLADIATE#226]

**Comment by emmettirl** [comment]
Stunned, (miss next turn)
Tattoo Revealed, (do ¾ damage, applied to enemies)
Countering, (damage anyone who damages you)
Crowd Pleased, (Draw cards and gain SP for every enemy defeated until end of turn)
Move Shouted, (while active, all cards worth 10 more SP)
Just Showed Off, (get showed off status when combo is matched)
Showed Off, (combo is worth 2x SP)
Double Damage, (i swear to god)
Stay Juggled, (Juggled status carries through to next turn)
Get Scars, (for Through Hardship These Scars, applies block at end of turn)

**Comment by soma-code** [comment]
Finished
