### ISSUE TITLE
Battle go worky

### ISSUE THREAD

**Issue by GrahamMOH** [Teicsoft/GLADIATE#54]
Constructing a single cycle of a combat turn using the previously built framework components.

**Comment by emmettirl** [comment]
Everyone get framework into main. 

Take in card, combo and enemy data from external source
- 4 card types (outside of scope this week, this week block gives health. )
- Data Files for cards with main values and ID to method in A central class, 
- Data file for combo orders, with ID to method in central class. 
- Write the data files, to translate game design work


Effect resolution
- Set Cards, resolve card effects, resolve combos, 
- Determine how combos work  (exact match L->R, order matters)
- multiple enemies + targeting


Player object / enemy object
- health pool
- turn state/order
- spectacle points/combo meter. 





- Stack as combo engine, wipe stack after each hand/ combo (out of scope this week)
- Grounding/ prone / air: interrupt combo ( out of scope for this week)

**Comment by emmettirl** [comment]
Sinead - Wed, Thur,
Cath - Thurs
Emmett - Wednesday

**Comment by emmettirl** [comment]
- [Player Object / Enemy Object](https://github.com/Teicsoft/SpectacleCardGame/issues/75)

**Comment by emmettirl** [comment]
ClardSleeve, is only real blocker
